SVCPLAN-851: Add custom yum_upgrade postscript can run as last postscript
ncsa/xcat-tools pull request #39
Opened 2022-05-17 21:51 UTC by billglick

Add a postscript that can do yum upgrades.

It runs `needs-restarting` to see if yum thinks a reboot is necessary and if so it schedules one via `shutdown -r +2`.

2022-05-18 16:05 UTC, billglick commented
I think we need to add a method of allowing RHEL to be locked to a specific EUS version. Otherwise this postscript risks updating, as an example, a RHEL 8.4 install to the latest (e.g. 8.6), before an admin has a chance to lock the release to 8.4 EUS.

Perhaps this is yet another new, optional custom postscript that should be run before the `yum_upgrade` postscript.

```
subscription-manager release --set=8.4
  # Enable the EUS repos
  subscription-manager repos --enable=rhel-8-for-x86_64-appstream-eus-rpms
  subscription-manager repos --enable=rhel-8-for-x86_64-baseos-eus-rpms
  subscription-manager repos --enable=codeready-builder-for-rhel-8-x86_64-eus-rpms
```

2022-05-18 18:48 UTC, billglick commented on postscripts/yum_upgrade
> +[ $(/bin/needs-restarting -r >/dev/null ) ] && {
We need a better check for seeing if we need to reboot. So far `needs-restarting` has never shown that we need to reboot.

But I've seen the `yum upgrade` update the kernel, which I think should trigger the scheduled reboot.

2022-05-18 19:39 UTC, billglick commented on postscripts/yum_upgrade
> +[ $(/bin/needs-restarting -r >/dev/null ) ] && {
One solution would just be for `yum_upgrade` to always schedule a reboot. And/or default to rebooting, but provide an option to skip scheduling a reboot if that is desired.

2022-05-19 15:21 UTC, bsper2 requested changes
Would be nice to rename postscripts/rhel_eus to something that makes it more clear what the script does.

Something like rhel_set_release rhel_version_lock rhel_lock_version rhel_release_lock rhel_release_set or something else if you think of a better name.

2022-05-19 15:29 UTC, billglick commented
I'll change `rhel_eus` to be `rhel_release_set`. 

That naming matches closely to the `subscription-manager release --set=8.4` that actually happens in the script.

2022-05-19 15:55 UTC, bsper2 approved these changes
Looks good thanks for the change.

2022-05-19 17:15 UTC, merged