SVCPLAN-4965: add check_keytab postscript
ncsa/xcat-tools pull request #62
Opened 2024-08-29 22:12 UTC by jakerundall

2024-08-29 22:13 UTC, jakerundall commented
The check_keytab postscript makes sure that a keytab doesn't contain stale host principals. The goal is to identify this problem promptly on boot rather than finding out due to user reports, etc.

I've been testing this on MG since May.

2024-08-29 22:28 UTC, billglick requested changes
The name of the postscript is wrong in the --help option.

2024-08-29 22:28 UTC, billglick commented on postscripts/check_keytab
> +    puppet_run [OPTIONS] [ENV_NAME]
```suggestion
    check_keytab [OPTIONS]
```

2024-08-29 22:28 UTC, billglick commented on postscripts/check_keytab
> +PRINCIPAL="host/"`hostname -f`"@NCSA.EDU"
I am worried that there may be cases where `hostname -f` intentionally doesn't match the hostname of the host's kerberos principal. I can't come up with an example at the moment, but I guess that is the point of optionally being able to pass in the host principal name.

No change needed. Just thinking out loud.

2024-08-29 22:30 UTC, billglick commented
There was a part of me that questioned if we should move bad keytab file aside so that theoretically Puppet could fix it. But after thinking about that for a few minutes, I realized some manual clean up will almost always be required if that is the case.

2024-08-29 22:37 UTC, jakerundall commented on postscripts/check_keytab
> +    puppet_run [OPTIONS] [ENV_NAME]
Fixed, thanks!

2024-08-29 22:40 UTC, jakerundall commented
> There was a part of me that questioned if we should move bad keytab file aside so that theoretically Puppet could fix it. But after thinking about that for a few minutes, I realized some manual clean up will almost always be required if that is the case.

It definitely _could_ do that. And we could also update Puppet to delete any host principal that already exists in that case so it can recreate it. However I think we generally use createhost principals, which can only create and not delete AFAIK, for Puppet. But something to think about.

2024-09-05 15:27 UTC, billglick approved these changes

2024-09-05 16:53 UTC, merged